//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEventos.SRefTipoParticipante {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoParticipante", Namespace="http://schemas.datacontract.org/2004/07/Sise.Entities")]
    [System.SerializableAttribute()]
    public partial class TipoParticipante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodTipoParticipanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreTipoParticipanteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodTipoParticipante {
            get {
                return this.CodTipoParticipanteField;
            }
            set {
                if ((this.CodTipoParticipanteField.Equals(value) != true)) {
                    this.CodTipoParticipanteField = value;
                    this.RaisePropertyChanged("CodTipoParticipante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreTipoParticipante {
            get {
                return this.NombreTipoParticipanteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreTipoParticipanteField, value) != true)) {
                    this.NombreTipoParticipanteField = value;
                    this.RaisePropertyChanged("NombreTipoParticipante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponse", Namespace="http://schemas.datacontract.org/2004/07/Sise.WcfService.Entity")]
    [System.SerializableAttribute()]
    public partial class ServiceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageDevField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageDev {
            get {
                return this.MessageDevField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageDevField, value) != true)) {
                    this.MessageDevField = value;
                    this.RaisePropertyChanged("MessageDev");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRefTipoParticipante.ITipoParticipanteService")]
    public interface ITipoParticipanteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipoParticipanteService/registrar", ReplyAction="http://tempuri.org/ITipoParticipanteService/registrarResponse")]
        WebEventos.SRefTipoParticipante.ServiceResponse registrar(WebEventos.SRefTipoParticipante.TipoParticipante tipoParticipantes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipoParticipanteService/registrar", ReplyAction="http://tempuri.org/ITipoParticipanteService/registrarResponse")]
        System.Threading.Tasks.Task<WebEventos.SRefTipoParticipante.ServiceResponse> registrarAsync(WebEventos.SRefTipoParticipante.TipoParticipante tipoParticipantes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipoParticipanteService/actualizar", ReplyAction="http://tempuri.org/ITipoParticipanteService/actualizarResponse")]
        WebEventos.SRefTipoParticipante.ServiceResponse actualizar(WebEventos.SRefTipoParticipante.TipoParticipante tipoParticipantes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipoParticipanteService/actualizar", ReplyAction="http://tempuri.org/ITipoParticipanteService/actualizarResponse")]
        System.Threading.Tasks.Task<WebEventos.SRefTipoParticipante.ServiceResponse> actualizarAsync(WebEventos.SRefTipoParticipante.TipoParticipante tipoParticipantes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipoParticipanteService/eliminar", ReplyAction="http://tempuri.org/ITipoParticipanteService/eliminarResponse")]
        WebEventos.SRefTipoParticipante.ServiceResponse eliminar(int CodTipoParticipantes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipoParticipanteService/eliminar", ReplyAction="http://tempuri.org/ITipoParticipanteService/eliminarResponse")]
        System.Threading.Tasks.Task<WebEventos.SRefTipoParticipante.ServiceResponse> eliminarAsync(int CodTipoParticipantes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipoParticipanteService/listar", ReplyAction="http://tempuri.org/ITipoParticipanteService/listarResponse")]
        WebEventos.SRefTipoParticipante.TipoParticipante[] listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipoParticipanteService/listar", ReplyAction="http://tempuri.org/ITipoParticipanteService/listarResponse")]
        System.Threading.Tasks.Task<WebEventos.SRefTipoParticipante.TipoParticipante[]> listarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipoParticipanteService/buscar", ReplyAction="http://tempuri.org/ITipoParticipanteService/buscarResponse")]
        WebEventos.SRefTipoParticipante.TipoParticipante buscar(int CodTipoParticipantes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipoParticipanteService/buscar", ReplyAction="http://tempuri.org/ITipoParticipanteService/buscarResponse")]
        System.Threading.Tasks.Task<WebEventos.SRefTipoParticipante.TipoParticipante> buscarAsync(int CodTipoParticipantes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITipoParticipanteServiceChannel : WebEventos.SRefTipoParticipante.ITipoParticipanteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipoParticipanteServiceClient : System.ServiceModel.ClientBase<WebEventos.SRefTipoParticipante.ITipoParticipanteService>, WebEventos.SRefTipoParticipante.ITipoParticipanteService {
        
        public TipoParticipanteServiceClient() {
        }
        
        public TipoParticipanteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TipoParticipanteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoParticipanteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoParticipanteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebEventos.SRefTipoParticipante.ServiceResponse registrar(WebEventos.SRefTipoParticipante.TipoParticipante tipoParticipantes) {
            return base.Channel.registrar(tipoParticipantes);
        }
        
        public System.Threading.Tasks.Task<WebEventos.SRefTipoParticipante.ServiceResponse> registrarAsync(WebEventos.SRefTipoParticipante.TipoParticipante tipoParticipantes) {
            return base.Channel.registrarAsync(tipoParticipantes);
        }
        
        public WebEventos.SRefTipoParticipante.ServiceResponse actualizar(WebEventos.SRefTipoParticipante.TipoParticipante tipoParticipantes) {
            return base.Channel.actualizar(tipoParticipantes);
        }
        
        public System.Threading.Tasks.Task<WebEventos.SRefTipoParticipante.ServiceResponse> actualizarAsync(WebEventos.SRefTipoParticipante.TipoParticipante tipoParticipantes) {
            return base.Channel.actualizarAsync(tipoParticipantes);
        }
        
        public WebEventos.SRefTipoParticipante.ServiceResponse eliminar(int CodTipoParticipantes) {
            return base.Channel.eliminar(CodTipoParticipantes);
        }
        
        public System.Threading.Tasks.Task<WebEventos.SRefTipoParticipante.ServiceResponse> eliminarAsync(int CodTipoParticipantes) {
            return base.Channel.eliminarAsync(CodTipoParticipantes);
        }
        
        public WebEventos.SRefTipoParticipante.TipoParticipante[] listar() {
            return base.Channel.listar();
        }
        
        public System.Threading.Tasks.Task<WebEventos.SRefTipoParticipante.TipoParticipante[]> listarAsync() {
            return base.Channel.listarAsync();
        }
        
        public WebEventos.SRefTipoParticipante.TipoParticipante buscar(int CodTipoParticipantes) {
            return base.Channel.buscar(CodTipoParticipantes);
        }
        
        public System.Threading.Tasks.Task<WebEventos.SRefTipoParticipante.TipoParticipante> buscarAsync(int CodTipoParticipantes) {
            return base.Channel.buscarAsync(CodTipoParticipantes);
        }
    }
}
