//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAuditoriaEventos.Auditoria_Paticipante_por_UsuarioService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auditoria_Paticipante_por_Usuario", Namespace="http://schemas.datacontract.org/2004/07/Sise.Entities")]
    [System.SerializableAttribute()]
    public partial class Auditoria_Paticipante_por_Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodAuditoriaPart_UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodParticipanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Email_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Accion {
            get {
                return this.AccionField;
            }
            set {
                if ((object.ReferenceEquals(this.AccionField, value) != true)) {
                    this.AccionField = value;
                    this.RaisePropertyChanged("Accion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodAuditoriaPart_User {
            get {
                return this.CodAuditoriaPart_UserField;
            }
            set {
                if ((this.CodAuditoriaPart_UserField.Equals(value) != true)) {
                    this.CodAuditoriaPart_UserField = value;
                    this.RaisePropertyChanged("CodAuditoriaPart_User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodParticipante {
            get {
                return this.CodParticipanteField;
            }
            set {
                if ((this.CodParticipanteField.Equals(value) != true)) {
                    this.CodParticipanteField = value;
                    this.RaisePropertyChanged("CodParticipante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email_usuario {
            get {
                return this.Email_usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.Email_usuarioField, value) != true)) {
                    this.Email_usuarioField = value;
                    this.RaisePropertyChanged("Email_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponse", Namespace="http://schemas.datacontract.org/2004/07/Sise.WcfService.Entity")]
    [System.SerializableAttribute()]
    public partial class ServiceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageDevField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageDev {
            get {
                return this.MessageDevField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageDevField, value) != true)) {
                    this.MessageDevField = value;
                    this.RaisePropertyChanged("MessageDev");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Auditoria_Paticipante_por_UsuarioService.IAuditoria_Paticipante_por_UsuarioServic" +
        "e")]
    public interface IAuditoria_Paticipante_por_UsuarioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuditoria_Paticipante_por_UsuarioService/registrar", ReplyAction="http://tempuri.org/IAuditoria_Paticipante_por_UsuarioService/registrarResponse")]
        AppAuditoriaEventos.Auditoria_Paticipante_por_UsuarioService.ServiceResponse registrar(AppAuditoriaEventos.Auditoria_Paticipante_por_UsuarioService.Auditoria_Paticipante_por_Usuario auditoriaparticipanteporusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuditoria_Paticipante_por_UsuarioService/registrar", ReplyAction="http://tempuri.org/IAuditoria_Paticipante_por_UsuarioService/registrarResponse")]
        System.Threading.Tasks.Task<AppAuditoriaEventos.Auditoria_Paticipante_por_UsuarioService.ServiceResponse> registrarAsync(AppAuditoriaEventos.Auditoria_Paticipante_por_UsuarioService.Auditoria_Paticipante_por_Usuario auditoriaparticipanteporusuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuditoria_Paticipante_por_UsuarioServiceChannel : AppAuditoriaEventos.Auditoria_Paticipante_por_UsuarioService.IAuditoria_Paticipante_por_UsuarioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Auditoria_Paticipante_por_UsuarioServiceClient : System.ServiceModel.ClientBase<AppAuditoriaEventos.Auditoria_Paticipante_por_UsuarioService.IAuditoria_Paticipante_por_UsuarioService>, AppAuditoriaEventos.Auditoria_Paticipante_por_UsuarioService.IAuditoria_Paticipante_por_UsuarioService {
        
        public Auditoria_Paticipante_por_UsuarioServiceClient() {
        }
        
        public Auditoria_Paticipante_por_UsuarioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Auditoria_Paticipante_por_UsuarioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Auditoria_Paticipante_por_UsuarioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Auditoria_Paticipante_por_UsuarioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AppAuditoriaEventos.Auditoria_Paticipante_por_UsuarioService.ServiceResponse registrar(AppAuditoriaEventos.Auditoria_Paticipante_por_UsuarioService.Auditoria_Paticipante_por_Usuario auditoriaparticipanteporusuario) {
            return base.Channel.registrar(auditoriaparticipanteporusuario);
        }
        
        public System.Threading.Tasks.Task<AppAuditoriaEventos.Auditoria_Paticipante_por_UsuarioService.ServiceResponse> registrarAsync(AppAuditoriaEventos.Auditoria_Paticipante_por_UsuarioService.Auditoria_Paticipante_por_Usuario auditoriaparticipanteporusuario) {
            return base.Channel.registrarAsync(auditoriaparticipanteporusuario);
        }
    }
}
