//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEventos.SRefParticipante {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Participante", Namespace="http://schemas.datacontract.org/2004/07/Sise.Entities")]
    [System.SerializableAttribute()]
    public partial class Participante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodParticipanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodTipoParticipanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodParticipante {
            get {
                return this.CodParticipanteField;
            }
            set {
                if ((this.CodParticipanteField.Equals(value) != true)) {
                    this.CodParticipanteField = value;
                    this.RaisePropertyChanged("CodParticipante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodTipoParticipante {
            get {
                return this.CodTipoParticipanteField;
            }
            set {
                if ((this.CodTipoParticipanteField.Equals(value) != true)) {
                    this.CodTipoParticipanteField = value;
                    this.RaisePropertyChanged("CodTipoParticipante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni {
            get {
                return this.DniField;
            }
            set {
                if ((object.ReferenceEquals(this.DniField, value) != true)) {
                    this.DniField = value;
                    this.RaisePropertyChanged("Dni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNac {
            get {
                return this.FechaNacField;
            }
            set {
                if ((this.FechaNacField.Equals(value) != true)) {
                    this.FechaNacField = value;
                    this.RaisePropertyChanged("FechaNac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponse", Namespace="http://schemas.datacontract.org/2004/07/Sise.WcfService.Entity")]
    [System.SerializableAttribute()]
    public partial class ServiceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageDevField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageDev {
            get {
                return this.MessageDevField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageDevField, value) != true)) {
                    this.MessageDevField = value;
                    this.RaisePropertyChanged("MessageDev");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRefParticipante.IParticipanteService")]
    public interface IParticipanteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParticipanteService/registrar", ReplyAction="http://tempuri.org/IParticipanteService/registrarResponse")]
        WebEventos.SRefParticipante.ServiceResponse registrar(WebEventos.SRefParticipante.Participante participante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParticipanteService/registrar", ReplyAction="http://tempuri.org/IParticipanteService/registrarResponse")]
        System.Threading.Tasks.Task<WebEventos.SRefParticipante.ServiceResponse> registrarAsync(WebEventos.SRefParticipante.Participante participante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParticipanteService/actualizar", ReplyAction="http://tempuri.org/IParticipanteService/actualizarResponse")]
        WebEventos.SRefParticipante.ServiceResponse actualizar(WebEventos.SRefParticipante.Participante participante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParticipanteService/actualizar", ReplyAction="http://tempuri.org/IParticipanteService/actualizarResponse")]
        System.Threading.Tasks.Task<WebEventos.SRefParticipante.ServiceResponse> actualizarAsync(WebEventos.SRefParticipante.Participante participante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParticipanteService/eliminar", ReplyAction="http://tempuri.org/IParticipanteService/eliminarResponse")]
        WebEventos.SRefParticipante.ServiceResponse eliminar(int CodParticipante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParticipanteService/eliminar", ReplyAction="http://tempuri.org/IParticipanteService/eliminarResponse")]
        System.Threading.Tasks.Task<WebEventos.SRefParticipante.ServiceResponse> eliminarAsync(int CodParticipante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParticipanteService/listar", ReplyAction="http://tempuri.org/IParticipanteService/listarResponse")]
        WebEventos.SRefParticipante.Participante[] listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParticipanteService/listar", ReplyAction="http://tempuri.org/IParticipanteService/listarResponse")]
        System.Threading.Tasks.Task<WebEventos.SRefParticipante.Participante[]> listarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParticipanteService/buscar", ReplyAction="http://tempuri.org/IParticipanteService/buscarResponse")]
        WebEventos.SRefParticipante.Participante buscar(int CodParticipante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParticipanteService/buscar", ReplyAction="http://tempuri.org/IParticipanteService/buscarResponse")]
        System.Threading.Tasks.Task<WebEventos.SRefParticipante.Participante> buscarAsync(int CodParticipante);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IParticipanteServiceChannel : WebEventos.SRefParticipante.IParticipanteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParticipanteServiceClient : System.ServiceModel.ClientBase<WebEventos.SRefParticipante.IParticipanteService>, WebEventos.SRefParticipante.IParticipanteService {
        
        public ParticipanteServiceClient() {
        }
        
        public ParticipanteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParticipanteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParticipanteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParticipanteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebEventos.SRefParticipante.ServiceResponse registrar(WebEventos.SRefParticipante.Participante participante) {
            return base.Channel.registrar(participante);
        }
        
        public System.Threading.Tasks.Task<WebEventos.SRefParticipante.ServiceResponse> registrarAsync(WebEventos.SRefParticipante.Participante participante) {
            return base.Channel.registrarAsync(participante);
        }
        
        public WebEventos.SRefParticipante.ServiceResponse actualizar(WebEventos.SRefParticipante.Participante participante) {
            return base.Channel.actualizar(participante);
        }
        
        public System.Threading.Tasks.Task<WebEventos.SRefParticipante.ServiceResponse> actualizarAsync(WebEventos.SRefParticipante.Participante participante) {
            return base.Channel.actualizarAsync(participante);
        }
        
        public WebEventos.SRefParticipante.ServiceResponse eliminar(int CodParticipante) {
            return base.Channel.eliminar(CodParticipante);
        }
        
        public System.Threading.Tasks.Task<WebEventos.SRefParticipante.ServiceResponse> eliminarAsync(int CodParticipante) {
            return base.Channel.eliminarAsync(CodParticipante);
        }
        
        public WebEventos.SRefParticipante.Participante[] listar() {
            return base.Channel.listar();
        }
        
        public System.Threading.Tasks.Task<WebEventos.SRefParticipante.Participante[]> listarAsync() {
            return base.Channel.listarAsync();
        }
        
        public WebEventos.SRefParticipante.Participante buscar(int CodParticipante) {
            return base.Channel.buscar(CodParticipante);
        }
        
        public System.Threading.Tasks.Task<WebEventos.SRefParticipante.Participante> buscarAsync(int CodParticipante) {
            return base.Channel.buscarAsync(CodParticipante);
        }
    }
}
